"use client";
import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { Plus, Search, UserRound, X, ExternalLink } from "lucide-react";

type Client = { id: string; name: string; email: string; phone?: string; whatsapp?: string; document?: string; city?: string; notes?: string; status?: boolean; orderCount?: number; totalSpent?: number };
const money = (n: number) => `$${Number(n || 0).toLocaleString("es-CO")}`;

export default function ClientsPage() {
  const [clients, setClients] = useState<Client[]>([]), [q, setQ] = useState(""), [open, setOpen] = useState(false), [saving, setSaving] = useState(false), [message, setMessage] = useState("");
  const [form, setForm] = useState({ name: "", email: "", phone: "", whatsapp: "", document: "", city: "", address: "", notes: "" });
  const load = async () => { const r = await fetch("/api/clients", { cache: "no-store" }); const d = await r.json(); if (r.ok) setClients(d); else setMessage(d.error || "No se pudieron cargar los clientes"); };
  useEffect(() => { void load(); }, []);
  const filtered = useMemo(() => clients.filter(c => `${c.name} ${c.email} ${c.phone || ""} ${c.whatsapp || ""} ${c.document || ""}`.toLowerCase().includes(q.toLowerCase())), [clients, q]);
  const create = async () => { setSaving(true); setMessage(""); try { const r = await fetch("/api/clients", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(form) }); const d = await r.json(); if (!r.ok) throw new Error(d.error); setMessage(`Cliente creado. Acceso temporal: ${d.temporaryPassword}`); setOpen(false); setForm({ name: "", email: "", phone: "", whatsapp: "", document: "", city: "", address: "", notes: "" }); await load(); } catch (e) { setMessage(e instanceof Error ? e.message : "No se pudo crear el cliente"); } finally { setSaving(false); } };
  return <div className="space-y-6 p-4 sm:p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-2xl font-semibold">Clientes</h1><p className="text-sm text-muted-foreground">CRM: clientes, contacto, historial comercial y cartera.</p></div><button onClick={() => setOpen(true)} className="inline-flex h-10 items-center rounded-md bg-primary px-4 text-sm font-medium text-primary-foreground"><Plus className="mr-2 h-4 w-4" />Nuevo cliente</button></div>
    {message && <div className="rounded-md border p-3 text-sm">{message}</div>}
    <div className="relative"><Search className="absolute left-3 top-3 h-4 w-4 text-muted-foreground" /><input value={q} onChange={e => setQ(e.target.value)} placeholder="Buscar por nombre, correo, teléfono, WhatsApp o documento..." className="h-10 w-full rounded-md border bg-background pl-9 pr-3 text-sm" /></div>
    <div className="grid gap-3">{filtered.map(c => <div key={c.id} className="rounded-xl border p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="flex items-center gap-2 font-semibold"><UserRound className="h-4 w-4" />{c.name}</p><p className="mt-1 text-sm text-muted-foreground">{c.email} · {c.phone || "Sin teléfono"} · WhatsApp: {c.whatsapp || "—"}</p><p className="mt-1 text-xs text-muted-foreground">Documento: {c.document || "—"} · Ciudad: {c.city || "—"}</p></div><span className="rounded-full border px-2 py-1 text-xs">{c.status === false ? "Inactivo" : "Activo"}</span></div><div className="mt-4 flex flex-wrap items-center gap-5 text-sm"><span><strong>{c.orderCount || 0}</strong> pedidos</span><span><strong>{money(c.totalSpent || 0)}</strong> comprado</span><Link href={`/admin/clients/${c.id}`} className="inline-flex items-center gap-1 font-medium text-primary hover:underline">Ver ficha <ExternalLink className="h-3.5 w-3.5" /></Link></div></div>)}{!filtered.length && <div className="rounded-xl border border-dashed p-10 text-center text-sm text-muted-foreground">No hay clientes que coincidan.</div>}</div>
    {open && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 p-4"><div className="w-full max-w-2xl rounded-xl border bg-background p-5"><div className="flex justify-between"><div><h2 className="text-lg font-semibold">Nuevo cliente</h2><p className="text-sm text-muted-foreground">Nombre y correo son obligatorios.</p></div><button onClick={() => setOpen(false)}><X className="h-5 w-5" /></button></div><div className="mt-4 grid gap-3 sm:grid-cols-2">{Object.entries(form).map(([key, value]) => <div key={key}><label className="text-xs font-medium capitalize">{key}</label><input value={value} onChange={e => setForm(f => ({ ...f, [key]: e.target.value }))} className="mt-1 h-10 w-full rounded-md border bg-background px-3 text-sm" /></div>)}</div><div className="mt-5 flex justify-end gap-2"><button onClick={() => setOpen(false)} className="rounded-md border px-4 py-2 text-sm">Cancelar</button><button disabled={saving || !form.name || !form.email} onClick={() => void create()} className="rounded-md bg-primary px-4 py-2 text-sm text-primary-foreground disabled:opacity-50">{saving ? "Guardando..." : "Crear cliente"}</button></div></div></div>}
  </div>;
}
