"use client";

import { FormEvent, useEffect, useState } from "react";
import { ArrowLeft, CalendarDays, CheckCircle2, ClipboardList, CreditCard, History, Loader2, Plus, Search, Smartphone, Wrench } from "lucide-react";
import Link from "next/link";
import Navbar from "@/components/layouts/Navbar";

const statuses = ["received", "diagnosis", "awaiting_approval", "repairing", "ready", "delivered", "cancelled"] as const;
const statusLabel: Record<string, string> = { received: "Recibido", diagnosis: "Diagnóstico", awaiting_approval: "Esperando aprobación", repairing: "Reparando", ready: "Listo", delivered: "Entregado", cancelled: "Cancelado" };

type Part = { id: string; productId: string; name: string; sku: string; quantity: number; unitPrice: number; subtotal: number; consumed: boolean; warehouseName?: string };
type Payment = { id: string; amount: number; paymentMethod: string; at: string; by?: string };
type HistoryItem = { status: string; at: string; by?: string };
type Repair = {
  id: string; orderNumber: string; customer: string; phone: string; device: string; imei: string; serial: string; issue: string; status: string;
  total: number; paid: number; balance: number; createdAt: string; updatedAt?: string; notes?: string; technicianNotes?: string; labor?: number; discount?: number;
  parts?: Part[]; payments?: Payment[]; statusHistory?: HistoryItem[]; warrantyDays?: number; warrantyUntil?: string | null; estimatedDelivery?: string | null; deliveredAt?: string | null;
};

const money = (n: number) => new Intl.NumberFormat("es-CO", { style: "currency", currency: "COP", maximumFractionDigits: 0 }).format(n || 0);
const dateTime = (value?: string | null) => value ? new Intl.DateTimeFormat("es-CO", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)) : "—";

export default function ServiceOrdersPage() {
  const [orders, setOrders] = useState<Repair[]>([]), [search, setSearch] = useState(""), [status, setStatus] = useState(""), [loading, setLoading] = useState(true), [saving, setSaving] = useState(false), [error, setError] = useState("");
  const [selected, setSelected] = useState<Repair | null>(null), [detailLoading, setDetailLoading] = useState(false), [detailSaving, setDetailSaving] = useState(false), [detailError, setDetailError] = useState("");
  const [form, setForm] = useState({ customer: "", phone: "", deviceType: "phone", brand: "Apple", model: "", imei: "", serial: "", issue: "", total: "0", paid: "0" });
  const [detailForm, setDetailForm] = useState({ status: "received", notes: "", estimatedDelivery: "", warrantyDays: "30", labor: "0", discount: "0" });
  const [payment, setPayment] = useState({ amount: "", method: "cash" });

  const load = async () => { setLoading(true); try { const q = new URLSearchParams(); if (search.trim()) q.set("search", search.trim()); if (status) q.set("status", status); const r = await fetch(`/api/service-orders?${q}`, { cache: "no-store" }); const d = await r.json(); if (!r.ok) throw new Error(d.error); setOrders(d.orders ?? []); if (selected) { const fresh = (d.orders ?? []).find((o: Repair) => o.id === selected.id); if (fresh) setSelected(fresh); } } catch (e) { setError(e instanceof Error ? e.message : "No se pudieron cargar las reparaciones"); } finally { setLoading(false); } };
  useEffect(() => { load(); }, [status]);

  const openDetail = async (order: Repair) => {
    setSelected(order); setDetailError(""); setDetailLoading(true);
    try { const r = await fetch(`/api/service-orders?search=${encodeURIComponent(order.id)}`, { cache: "no-store" }); const d = await r.json(); if (!r.ok) throw new Error(d.error); const fresh = d.orders?.[0] ?? order; setSelected(fresh); setDetailForm({ status: fresh.status, notes: fresh.notes ?? "", estimatedDelivery: fresh.estimatedDelivery ? new Date(fresh.estimatedDelivery).toISOString().slice(0, 16) : "", warrantyDays: String(fresh.warrantyDays ?? 30), labor: String(fresh.labor ?? 0), discount: String(fresh.discount ?? 0) }); } catch (e) { setDetailError(e instanceof Error ? e.message : "No se pudo cargar el detalle"); } finally { setDetailLoading(false); }
  };

  const set = (key: string, value: string) => setForm(f => ({ ...f, [key]: value }));
  const setDetail = (key: string, value: string) => setDetailForm(f => ({ ...f, [key]: value }));

  async function submit(e: FormEvent) { e.preventDefault(); setSaving(true); setError(""); try { const r = await fetch("/api/service-orders", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...form, total: Number(form.total || 0), paid: Number(form.paid || 0) }) }); const d = await r.json(); if (!r.ok) throw new Error(d.error); setForm({ customer: "", phone: "", deviceType: "phone", brand: "Apple", model: "", imei: "", serial: "", issue: "", total: "0", paid: "0" }); await load(); } catch (e) { setError(e instanceof Error ? e.message : "No se pudo crear la orden"); } finally { setSaving(false); } }

  async function updateLifecycle() {
    if (!selected) return; setDetailSaving(true); setDetailError("");
    try { const r = await fetch("/api/service-orders/lifecycle", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id: selected.id, status: detailForm.status, notes: detailForm.notes, estimatedDelivery: detailForm.estimatedDelivery || null, warrantyDays: Number(detailForm.warrantyDays || 0) }) }); const d = await r.json(); if (!r.ok) throw new Error(d.error); await openDetail(selected); await load(); } catch (e) { setDetailError(e instanceof Error ? e.message : "No se pudo actualizar la orden"); } finally { setDetailSaving(false); }
  }

  async function updateAmount(action: "set_labor" | "set_discount", amount: string) {
    if (!selected) return; setDetailSaving(true); setDetailError("");
    try { const r = await fetch("/api/service-orders", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id: selected.id, action, amount: Number(amount || 0) }) }); const d = await r.json(); if (!r.ok) throw new Error(d.error); setSelected(d); setDetailForm(f => ({ ...f, labor: String(d.labor ?? 0), discount: String(d.discount ?? 0) })); await load(); } catch (e) { setDetailError(e instanceof Error ? e.message : "No se pudo actualizar el valor"); } finally { setDetailSaving(false); }
  }

  async function addPayment(e: FormEvent) {
    e.preventDefault(); if (!selected) return; setDetailSaving(true); setDetailError("");
    try { const r = await fetch("/api/service-orders", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id: selected.id, action: "payment", amount: Number(payment.amount || 0), paymentMethod: payment.method }) }); const d = await r.json(); if (!r.ok) throw new Error(d.error); setSelected(d); setPayment({ amount: "", method: "cash" }); await load(); } catch (e) { setDetailError(e instanceof Error ? e.message : "No se pudo registrar el pago"); } finally { setDetailSaving(false); }
  }

  const input = (key: keyof typeof form, label: string, required = false) => <label className="block"><span className="mb-1 block text-xs font-medium text-muted-foreground">{label}{required ? " *" : ""}</span><input required={required} value={form[key]} onChange={e => set(key, e.target.value)} className="h-10 w-full rounded-xl border bg-background px-3 text-sm" /></label>;

  return <Navbar><main className="min-h-screen p-4 sm:p-8"><div className="mx-auto max-w-7xl space-y-6">
    <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex items-center gap-2"><ClipboardList className="h-5 w-5 text-violet-500" /><h1 className="text-2xl font-semibold">Reparaciones</h1></div><p className="mt-1 text-sm text-muted-foreground">Recepción, identificación y seguimiento de equipos en servicio.</p></div><Link href="/devices" className="inline-flex items-center gap-2 rounded-xl border px-4 py-2 text-sm"><Smartphone className="h-4 w-4" />Equipos DarkPhone</Link></div>
    {error && <div className="rounded-xl border border-destructive/30 bg-destructive/5 p-3 text-sm text-destructive">{error}</div>}
    <section className="rounded-2xl border bg-background p-5 shadow-sm"><div className="mb-4 flex items-center gap-2"><Plus className="h-4 w-4" /><h2 className="font-semibold">Recibir equipo</h2></div><form onSubmit={submit} className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{input("customer", "Cliente", true)}{input("phone", "Teléfono", true)}{input("brand", "Marca", true)}{input("model", "Modelo / equipo", true)}{input("imei", "IMEI")}{input("serial", "Serial")}{input("total", "Total", true)}{input("paid", "Abono")}{<label className="block sm:col-span-2 lg:col-span-4"><span className="mb-1 block text-xs font-medium text-muted-foreground">Falla reportada *</span><textarea required value={form.issue} onChange={e => set("issue", e.target.value)} className="min-h-24 w-full rounded-xl border bg-background p-3 text-sm" /></label>}<div className="flex justify-end sm:col-span-2 lg:col-span-4"><button disabled={saving} className="rounded-xl bg-primary px-5 py-2.5 text-sm font-medium text-primary-foreground disabled:opacity-50">{saving ? "Registrando..." : "Recibir equipo"}</button></div></form></section>
    <section className="rounded-2xl border bg-background shadow-sm"><div className="flex flex-col gap-3 border-b p-4 sm:flex-row"><div className="flex flex-1 items-center gap-2 rounded-xl border px-3"><Search className="h-4 w-4 text-muted-foreground" /><input value={search} onChange={e => setSearch(e.target.value)} onKeyDown={e => e.key === "Enter" && load()} placeholder="Buscar cliente, equipo, IMEI, serial o falla..." className="h-10 flex-1 bg-transparent text-sm outline-none" /></div><select value={status} onChange={e => setStatus(e.target.value)} className="h-10 rounded-xl border bg-background px-3 text-sm"><option value="">Todos los estados</option>{statuses.map(s => <option key={s} value={s}>{statusLabel[s]}</option>)}</select></div>{loading ? <div className="p-8 text-sm text-muted-foreground">Cargando reparaciones...</div> : orders.length === 0 ? <div className="p-8 text-sm text-muted-foreground">No hay órdenes de reparación para mostrar.</div> : <div className="divide-y">{orders.map(o => <div key={o.id} className="grid gap-3 p-4 sm:grid-cols-[1fr_auto] sm:items-center"><button type="button" onClick={() => openDetail(o)} className="text-left"><div className="flex flex-wrap items-center gap-2"><span className="font-medium">{o.orderNumber}</span><span className="rounded-full border px-2 py-0.5 text-xs">{statusLabel[o.status] ?? o.status}</span></div><div className="mt-1 text-sm">{o.customer} · {o.phone}</div><div className="text-sm text-muted-foreground">{o.device}{o.imei ? ` · IMEI ${o.imei}` : o.serial ? ` · Serial ${o.serial}` : ""}</div><div className="mt-1 line-clamp-2 text-sm text-muted-foreground">{o.issue}</div></button><div className="flex items-center justify-between gap-4 sm:justify-end"><div className="text-left sm:text-right"><div className="text-sm font-medium">{money(o.total)}</div><div className="text-xs text-muted-foreground">Saldo: {money(o.balance)}</div></div><button type="button" onClick={() => openDetail(o)} className="rounded-xl border px-3 py-2 text-xs font-medium hover:bg-muted">Ver detalle</button></div></div>)}</div>}</section>

    {selected && <section className="rounded-2xl border bg-background shadow-sm"><div className="flex flex-col gap-3 border-b p-5 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex items-center gap-2"><Wrench className="h-5 w-5 text-violet-500" /><h2 className="text-xl font-semibold">Orden {selected.orderNumber}</h2><span className="rounded-full border px-2 py-0.5 text-xs">{statusLabel[selected.status] ?? selected.status}</span></div><p className="mt-1 text-sm text-muted-foreground">{selected.customer} · {selected.phone} · {selected.device}</p></div><button type="button" onClick={() => setSelected(null)} className="inline-flex items-center gap-2 rounded-xl border px-3 py-2 text-sm"><ArrowLeft className="h-4 w-4" />Cerrar detalle</button></div>
      {detailLoading ? <div className="flex items-center gap-2 p-8 text-sm text-muted-foreground"><Loader2 className="h-4 w-4 animate-spin" />Cargando detalle...</div> : <div className="grid gap-5 p-5 lg:grid-cols-3">
        {detailError && <div className="rounded-xl border border-destructive/30 bg-destructive/5 p-3 text-sm text-destructive lg:col-span-3">{detailError}</div>}
        <div className="space-y-5 lg:col-span-2">
          <div className="grid gap-4 sm:grid-cols-2"><div className="rounded-xl border p-4"><div className="text-xs text-muted-foreground">Falla reportada</div><div className="mt-1 text-sm font-medium">{selected.issue || "—"}</div>{selected.imei && <div className="mt-2 text-xs text-muted-foreground">IMEI: {selected.imei}</div>}{selected.serial && <div className="text-xs text-muted-foreground">Serial: {selected.serial}</div>}</div><div className="rounded-xl border p-4"><div className="text-xs text-muted-foreground">Fechas</div><div className="mt-1 text-sm">Ingreso: {dateTime(selected.createdAt)}</div><div className="text-sm">Entrega estimada: {dateTime(selected.estimatedDelivery)}</div><div className="text-sm">Entregado: {dateTime(selected.deliveredAt)}</div></div></div>
          <div className="rounded-xl border p-4"><div className="mb-4 flex items-center gap-2"><CalendarDays className="h-4 w-4" /><h3 className="font-semibold">Estado y seguimiento</h3></div><div className="grid gap-4 sm:grid-cols-2"><label><span className="mb-1 block text-xs text-muted-foreground">Estado</span><select disabled={selected.status === "delivered" || selected.status === "cancelled"} value={detailForm.status} onChange={e => setDetail("status", e.target.value)} className="h-10 w-full rounded-xl border bg-background px-3 text-sm">{statuses.map(s => <option key={s} value={s}>{statusLabel[s]}</option>)}</select></label><label><span className="mb-1 block text-xs text-muted-foreground">Entrega estimada</span><input type="datetime-local" value={detailForm.estimatedDelivery} onChange={e => setDetail("estimatedDelivery", e.target.value)} className="h-10 w-full rounded-xl border bg-background px-3 text-sm" /></label><label><span className="mb-1 block text-xs text-muted-foreground">Garantía (días)</span><input type="number" min="0" max="3650" value={detailForm.warrantyDays} onChange={e => setDetail("warrantyDays", e.target.value)} className="h-10 w-full rounded-xl border bg-background px-3 text-sm" /></label><div className="flex items-end"><button disabled={detailSaving} onClick={updateLifecycle} className="inline-flex h-10 items-center gap-2 rounded-xl bg-primary px-4 text-sm font-medium text-primary-foreground disabled:opacity-50"><CheckCircle2 className="h-4 w-4" />Guardar seguimiento</button></div></div><label className="mt-4 block"><span className="mb-1 block text-xs text-muted-foreground">Notas / diagnóstico / trabajo realizado</span><textarea value={detailForm.notes} onChange={e => setDetail("notes", e.target.value)} className="min-h-28 w-full rounded-xl border bg-background p-3 text-sm" placeholder="Diagnóstico, observaciones, autorización del cliente, trabajo realizado..." /></label></div>
          <div className="rounded-xl border p-4"><div className="mb-4 flex items-center gap-2"><Wrench className="h-4 w-4" /><h3 className="font-semibold">Costos y repuestos</h3></div><div className="grid gap-3 sm:grid-cols-3"><label><span className="mb-1 block text-xs text-muted-foreground">Mano de obra</span><input type="number" min="0" value={detailForm.labor} onChange={e => setDetail("labor", e.target.value)} onBlur={() => updateAmount("set_labor", detailForm.labor)} className="h-10 w-full rounded-xl border bg-background px-3 text-sm" /></label><label><span className="mb-1 block text-xs text-muted-foreground">Descuento</span><input type="number" min="0" value={detailForm.discount} onChange={e => setDetail("discount", e.target.value)} onBlur={() => updateAmount("set_discount", detailForm.discount)} className="h-10 w-full rounded-xl border bg-background px-3 text-sm" /></label><div className="rounded-xl bg-muted/40 p-3"><div className="text-xs text-muted-foreground">Total actual</div><div className="text-lg font-semibold">{money(selected.total)}</div></div></div>{(selected.parts ?? []).length === 0 ? <div className="mt-4 rounded-xl border border-dashed p-4 text-sm text-muted-foreground">Aún no hay repuestos asociados a esta reparación.</div> : <div className="mt-4 overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b text-left text-xs text-muted-foreground"><th className="pb-2">Repuesto</th><th className="pb-2">Cant.</th><th className="pb-2">Valor</th><th className="pb-2">Inventario</th></tr></thead><tbody>{selected.parts!.map(p => <tr key={p.id} className="border-b last:border-0"><td className="py-2">{p.name}{p.sku && <span className="ml-2 text-xs text-muted-foreground">{p.sku}</span>}</td><td className="py-2">{p.quantity}</td><td className="py-2">{money(p.subtotal)}</td><td className="py-2">{p.consumed ? <span className="text-xs font-medium">Consumido{p.warehouseName ? ` · ${p.warehouseName}` : ""}</span> : <span className="text-xs text-muted-foreground">Pendiente</span>}</td></tr>)}</tbody></table></div>}</div>
        </div>
        <div className="space-y-5">
          <div className="rounded-xl border p-4"><div className="mb-4 flex items-center gap-2"><CreditCard className="h-4 w-4" /><h3 className="font-semibold">Pagos</h3></div><div className="space-y-1 text-sm"><div className="flex justify-between"><span>Total</span><strong>{money(selected.total)}</strong></div><div className="flex justify-between"><span>Pagado</span><span>{money(selected.paid)}</span></div><div className="flex justify-between border-t pt-2 font-semibold"><span>Saldo</span><span>{money(selected.balance)}</span></div></div>{selected.status !== "delivered" && selected.status !== "cancelled" && selected.balance > 0 && <form onSubmit={addPayment} className="mt-4 space-y-2"><input required type="number" min="1" max={selected.balance} value={payment.amount} onChange={e => setPayment(p => ({ ...p, amount: e.target.value }))} placeholder="Abono" className="h-10 w-full rounded-xl border bg-background px-3 text-sm" /><select value={payment.method} onChange={e => setPayment(p => ({ ...p, method: e.target.value }))} className="h-10 w-full rounded-xl border bg-background px-3 text-sm"><option value="cash">Efectivo</option><option value="card">Tarjeta</option><option value="transfer">Transferencia</option><option value="other">Otro</option></select><button disabled={detailSaving} className="w-full rounded-xl bg-primary px-4 py-2.5 text-sm font-medium text-primary-foreground disabled:opacity-50">Registrar abono</button></form>}{(selected.payments ?? []).length > 0 && <div className="mt-4 space-y-2">{selected.payments!.map(p => <div key={p.id} className="flex justify-between border-t pt-2 text-xs"><span>{dateTime(p.at)} · {p.paymentMethod}</span><strong>{money(p.amount)}</strong></div>)}</div>}</div>
          <div className="rounded-xl border p-4"><div className="mb-3 flex items-center gap-2"><History className="h-4 w-4" /><h3 className="font-semibold">Historial</h3></div><div className="space-y-3">{(selected.statusHistory ?? []).slice().reverse().map((h, i) => <div key={`${h.at}-${i}`} className="flex gap-3 text-sm"><div className="mt-1 h-2 w-2 shrink-0 rounded-full bg-violet-500" /><div><div className="font-medium">{statusLabel[h.status] ?? h.status}</div><div className="text-xs text-muted-foreground">{dateTime(h.at)}</div></div></div>)}</div></div>
          {selected.warrantyDays !== undefined && <div className="rounded-xl border p-4"><div className="text-xs text-muted-foreground">Garantía</div><div className="mt-1 font-semibold">{selected.warrantyDays} días</div><div className="text-xs text-muted-foreground">Vence: {dateTime(selected.warrantyUntil)}</div></div>}
        </div>
      </div>}
    </section>}
  </div></main></Navbar>;
}
