"use client";

import { FormEvent, useEffect, useState } from "react";
import { ClipboardList, Plus, Search, Smartphone } from "lucide-react";
import Link from "next/link";
import Navbar from "@/components/layouts/Navbar";

const statuses = ["received", "diagnosis", "awaiting_approval", "repairing", "ready", "delivered", "cancelled"] as const;
const statusLabel: Record<string, string> = { received: "Recibido", diagnosis: "Diagnóstico", awaiting_approval: "Esperando aprobación", repairing: "Reparando", ready: "Listo", delivered: "Entregado", cancelled: "Cancelado" };

type Repair = { id: string; orderNumber: string; customer: string; phone: string; device: string; imei: string; serial: string; issue: string; status: string; total: number; paid: number; balance: number; createdAt: string };

export default function ServiceOrdersPage() {
  const [orders, setOrders] = useState<Repair[]>([]), [search, setSearch] = useState(""), [status, setStatus] = useState(""), [loading, setLoading] = useState(true), [saving, setSaving] = useState(false), [error, setError] = useState("");
  const [form, setForm] = useState({ customer: "", phone: "", deviceType: "phone", brand: "Apple", model: "", imei: "", serial: "", issue: "", total: "0", paid: "0" });

  const load = async () => { setLoading(true); try { const q = new URLSearchParams(); if (search.trim()) q.set("search", search.trim()); if (status) q.set("status", status); const r = await fetch(`/api/service-orders?${q}`, { cache: "no-store" }); const d = await r.json(); if (!r.ok) throw new Error(d.error); setOrders(d.orders ?? []); } catch (e) { setError(e instanceof Error ? e.message : "No se pudieron cargar las reparaciones"); } finally { setLoading(false); } };
  useEffect(() => { load(); }, [status]);
  const set = (key: string, value: string) => setForm(f => ({ ...f, [key]: value }));
  async function submit(e: FormEvent) { e.preventDefault(); setSaving(true); setError(""); try { const r = await fetch("/api/service-orders", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...form, total: Number(form.total || 0), paid: Number(form.paid || 0) }) }); const d = await r.json(); if (!r.ok) throw new Error(d.error); setForm({ customer: "", phone: "", deviceType: "phone", brand: "Apple", model: "", imei: "", serial: "", issue: "", total: "0", paid: "0" }); await load(); } catch (e) { setError(e instanceof Error ? e.message : "No se pudo crear la orden"); } finally { setSaving(false); } }
  const money = (n: number) => new Intl.NumberFormat("es-CO", { style: "currency", currency: "COP", maximumFractionDigits: 0 }).format(n || 0);
  const input = (key: keyof typeof form, label: string, required = false) => <label className="block"><span className="mb-1 block text-xs font-medium text-muted-foreground">{label}{required ? " *" : ""}</span><input required={required} value={form[key]} onChange={e => set(key, e.target.value)} className="h-10 w-full rounded-xl border bg-background px-3 text-sm" /></label>;

  return <Navbar><main className="min-h-screen p-4 sm:p-8"><div className="mx-auto max-w-7xl space-y-6"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex items-center gap-2"><ClipboardList className="h-5 w-5 text-violet-500" /><h1 className="text-2xl font-semibold">Reparaciones</h1></div><p className="mt-1 text-sm text-muted-foreground">Recepción, identificación y seguimiento de equipos en servicio.</p></div><Link href="/devices" className="inline-flex items-center gap-2 rounded-xl border px-4 py-2 text-sm"><Smartphone className="h-4 w-4" />Equipos DarkPhone</Link></div>
  {error && <div className="rounded-xl border border-destructive/30 bg-destructive/5 p-3 text-sm text-destructive">{error}</div>}
  <section className="rounded-2xl border bg-background p-5 shadow-sm"><div className="mb-4 flex items-center gap-2"><Plus className="h-4 w-4" /><h2 className="font-semibold">Recibir equipo</h2></div><form onSubmit={submit} className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{input("customer", "Cliente", true)}{input("phone", "Teléfono", true)}{input("brand", "Marca", true)}{input("model", "Modelo / equipo", true)}{input("imei", "IMEI")}{input("serial", "Serial")}{input("total", "Total", true)}{input("paid", "Abono")}{<label className="block sm:col-span-2 lg:col-span-4"><span className="mb-1 block text-xs font-medium text-muted-foreground">Falla reportada *</span><textarea required value={form.issue} onChange={e => set("issue", e.target.value)} className="min-h-24 w-full rounded-xl border bg-background p-3 text-sm" /></label>}<div className="flex justify-end sm:col-span-2 lg:col-span-4"><button disabled={saving} className="rounded-xl bg-primary px-5 py-2.5 text-sm font-medium text-primary-foreground disabled:opacity-50">{saving ? "Registrando..." : "Recibir equipo"}</button></div></form></section>
  <section className="rounded-2xl border bg-background shadow-sm"><div className="flex flex-col gap-3 border-b p-4 sm:flex-row"><div className="flex flex-1 items-center gap-2 rounded-xl border px-3"><Search className="h-4 w-4 text-muted-foreground" /><input value={search} onChange={e => setSearch(e.target.value)} onKeyDown={e => e.key === "Enter" && load()} placeholder="Buscar cliente, equipo, IMEI, serial o falla..." className="h-10 flex-1 bg-transparent text-sm outline-none" /></div><select value={status} onChange={e => setStatus(e.target.value)} className="h-10 rounded-xl border bg-background px-3 text-sm"><option value="">Todos los estados</option>{statuses.map(s => <option key={s} value={s}>{statusLabel[s]}</option>)}</select></div>{loading ? <div className="p-8 text-sm text-muted-foreground">Cargando reparaciones...</div> : orders.length === 0 ? <div className="p-8 text-sm text-muted-foreground">No hay órdenes de reparación para mostrar.</div> : <div className="divide-y">{orders.map(o => <div key={o.id} className="grid gap-3 p-4 sm:grid-cols-[1fr_auto] sm:items-center"><div><div className="flex flex-wrap items-center gap-2"><span className="font-medium">{o.orderNumber}</span><span className="rounded-full border px-2 py-0.5 text-xs">{statusLabel[o.status] ?? o.status}</span></div><div className="mt-1 text-sm">{o.customer} · {o.phone}</div><div className="text-sm text-muted-foreground">{o.device}{o.imei ? ` · IMEI ${o.imei}` : o.serial ? ` · Serial ${o.serial}` : ""}</div><div className="mt-1 text-sm text-muted-foreground">{o.issue}</div></div><div className="text-left sm:text-right"><div className="text-sm font-medium">{money(o.total)}</div><div className="text-xs text-muted-foreground">Saldo: {money(o.balance)}</div></div></div>)}</div>}</section></div></main></Navbar>;
}
