"use client";
import { useCallback, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { ArrowLeft, CreditCard, FileText, History, RefreshCw, UserRound, Wrench } from "lucide-react";
import { Button } from "@/components/ui/button";

type Doc = { id: string; orderNumber: string; total: number; paid: number; balance: number; status: string; createdAt: string; paymentStatus?: string; deviceType?: string; brand?: string; model?: string; invoice?: { invoiceNumber: string; dueDate: string; status: string } | null };
type Data = { client: any; summary: { purchases: number; paid: number; balance: number; sales: number; repairs: number }; orders: Doc[]; repairs: Doc[]; payments: { id: string; type: string; number: string; amount: number; paymentMethod: string; createdAt: string }[] };
const money = (n: number) => new Intl.NumberFormat("es-CO", { style: "currency", currency: "COP", maximumFractionDigits: 0 }).format(n || 0);
const methodLabel: Record<string,string> = { cash: "Efectivo", card: "Tarjeta", transfer: "Transferencia", nequi: "Nequi", daviplata: "Daviplata", other: "Otro" };

export default function ClientDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const [id, setId] = useState(""); const [data, setData] = useState<Data | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const [pay, setPay] = useState<{ type: "sale"|"repair"; id: string; number: string; balance: number } | null>(null); const [amount, setAmount] = useState(""); const [method, setMethod] = useState("cash"); const [saving, setSaving] = useState(false); const [notice, setNotice] = useState("");
  useEffect(() => { void params.then(p => setId(p.id)); }, [params]);
  const load = useCallback(async () => { if (!id) return; setLoading(true); setError(""); try { const r = await fetch(`/api/clients/${id}`, { cache: "no-store" }); const d = await r.json(); if (!r.ok) throw new Error(d.error); setData(d); } catch (e) { setError(e instanceof Error ? e.message : "No se pudo cargar el cliente"); } finally { setLoading(false); } }, [id]);
  useEffect(() => { void load(); }, [load]);
  const pending = useMemo(() => [...(data?.orders || []).filter(x => x.balance > .009).map(x => ({ ...x, type: "sale" as const })), ...(data?.repairs || []).filter(x => x.balance > .009).map(x => ({ ...x, type: "repair" as const }))], [data]);
  const recordPayment = async () => { if (!pay) return; const value = Number(amount); if (!Number.isFinite(value) || value <= 0 || value > pay.balance + .009) { setNotice("Ingresa un abono válido que no supere el saldo."); return; } setSaving(true); setNotice(""); try { const r = await fetch(`/api/clients/${id}/payments`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ type: pay.type, documentId: pay.id, amount: value, paymentMethod: method }) }); const d = await r.json(); if (!r.ok) throw new Error(d.error); setPay(null); setAmount(""); setNotice("Abono registrado correctamente."); await load(); } catch (e) { setNotice(e instanceof Error ? e.message : "No se pudo registrar el abono"); } finally { setSaving(false); } };
  if (loading && !data) return <main className="p-6 text-sm text-muted-foreground">Cargando ficha...</main>;
  if (error) return <main className="space-y-4 p-6"><Link href="/admin/clients" className="inline-flex items-center gap-1 text-sm text-primary"><ArrowLeft className="h-4 w-4"/> Clientes</Link><div className="rounded-xl border p-6 text-sm">{error}</div></main>;
  if (!data) return null;
  const c = data.client;
  return <main className="space-y-6 p-4 sm:p-6">
    <header className="flex flex-wrap items-center justify-between gap-3"><div><Link href="/admin/clients" className="mb-3 inline-flex items-center gap-1 text-sm text-primary hover:underline"><ArrowLeft className="h-4 w-4"/> Clientes</Link><div className="flex items-center gap-2"><UserRound className="h-5 w-5"/><h1 className="text-2xl font-bold">{c.name}</h1></div><p className="text-sm text-muted-foreground">{c.email} · {c.phone || "Sin teléfono"} · Documento: {c.document || "—"}</p></div><Button variant="outline" onClick={load} disabled={loading}><RefreshCw className={`mr-2 h-4 w-4 ${loading ? "animate-spin" : ""}`}/>Actualizar</Button></header>
    {notice && <div className="rounded-xl border p-3 text-sm">{notice}</div>}
    <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><div className="rounded-2xl border p-5"><p className="text-sm text-muted-foreground">Total comprado</p><p className="mt-1 text-2xl font-bold">{money(data.summary.purchases)}</p></div><div className="rounded-2xl border p-5"><p className="text-sm text-muted-foreground">Total abonado</p><p className="mt-1 text-2xl font-bold">{money(data.summary.paid)}</p></div><div className="rounded-2xl border p-5"><p className="text-sm text-muted-foreground">Saldo pendiente</p><p className="mt-1 text-2xl font-bold">{money(data.summary.balance)}</p></div><div className="rounded-2xl border p-5"><p className="text-sm text-muted-foreground">Actividad</p><p className="mt-1 text-lg font-semibold">{data.summary.sales} ventas · {data.summary.repairs} reparaciones</p></div></div>
    <section className="rounded-2xl border p-5"><div className="mb-4 flex items-center gap-2"><FileText className="h-5 w-5"/><h2 className="font-semibold">Cuenta por cobrar</h2></div>{pending.length ? <div className="space-y-3">{pending.map(d => <div key={`${d.type}-${d.id}`} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border p-4"><div><p className="font-medium">{d.type === "sale" ? "Venta" : "Reparación"} · {d.orderNumber}</p><p className="text-xs text-muted-foreground">Total {money(d.total)} · Abonado {money(d.paid)} · Creado {new Date(d.createdAt).toLocaleDateString("es-CO")}{d.deviceType ? ` · ${d.brand} ${d.model}` : ""}</p></div><div className="flex items-center gap-3"><strong>{money(d.balance)}</strong><Button size="sm" onClick={() => setPay({ type: d.type, id: d.id, number: d.orderNumber, balance: d.balance })}><CreditCard className="mr-2 h-4 w-4"/>Registrar abono</Button></div></div>)}</div> : <p className="text-sm text-muted-foreground">Este cliente no tiene saldos pendientes.</p>}</section>
    <section className="rounded-2xl border p-5"><div className="mb-4 flex items-center gap-2"><History className="h-5 w-5"/><h2 className="font-semibold">Historial de pagos</h2></div>{data.payments.length ? <div className="divide-y">{data.payments.map(p => <div key={p.id} className="flex flex-wrap items-center justify-between gap-3 py-3 text-sm"><div><p className="font-medium">{p.type === "sale" ? "Venta" : "Reparación"} · {p.number}</p><p className="text-xs text-muted-foreground">{methodLabel[p.paymentMethod] || p.paymentMethod} · {new Date(p.createdAt).toLocaleString("es-CO")}</p></div><strong>{money(p.amount)}</strong></div>)}</div> : <p className="text-sm text-muted-foreground">Sin pagos registrados.</p>}</section>
    <section className="grid gap-4 lg:grid-cols-2"><div className="rounded-2xl border p-5"><h2 className="mb-3 font-semibold">Ventas</h2>{data.orders.length ? data.orders.slice(0, 10).map(o => <div key={o.id} className="border-b py-3 last:border-0"><p className="font-medium">{o.orderNumber}</p><p className="text-xs text-muted-foreground">{money(o.total)} · {o.paymentStatus || o.status} · {new Date(o.createdAt).toLocaleDateString("es-CO")}</p></div>) : <p className="text-sm text-muted-foreground">Sin ventas.</p>}</div><div className="rounded-2xl border p-5"><h2 className="mb-3 flex items-center gap-2 font-semibold"><Wrench className="h-4 w-4"/>Reparaciones</h2>{data.repairs.length ? data.repairs.slice(0, 10).map(o => <div key={o.id} className="border-b py-3 last:border-0"><p className="font-medium">{o.orderNumber}</p><p className="text-xs text-muted-foreground">{o.brand} {o.model} · {money(o.total)} · {o.status}</p></div>) : <p className="text-sm text-muted-foreground">Sin reparaciones.</p>}</div></section>
    {pay && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 p-4"><div className="w-full max-w-md rounded-2xl border bg-background p-5"><h2 className="text-lg font-semibold">Registrar abono</h2><p className="mt-1 text-sm text-muted-foreground">{pay.type === "sale" ? "Venta" : "Reparación"} {pay.number} · saldo {money(pay.balance)}</p><label className="mt-4 block text-sm font-medium">Monto<input type="number" min="1" max={pay.balance} value={amount} onChange={e => setAmount(e.target.value)} className="mt-1 h-10 w-full rounded-lg border bg-background px-3"/></label><label className="mt-3 block text-sm font-medium">Método<select value={method} onChange={e => setMethod(e.target.value)} className="mt-1 h-10 w-full rounded-lg border bg-background px-3"><option value="cash">Efectivo</option><option value="card">Tarjeta</option><option value="transfer">Transferencia</option><option value="nequi">Nequi</option><option value="daviplata">Daviplata</option><option value="other">Otro</option></select></label><div className="mt-5 flex justify-end gap-2"><Button variant="outline" onClick={() => setPay(null)}>Cancelar</Button><Button disabled={saving} onClick={() => void recordPayment()}>{saving ? "Guardando..." : "Registrar abono"}</Button></div></div></div>}
  </main>;
}
