"use client";

import { useEffect, useState } from "react";
import { ArrowDownCircle, ArrowUpCircle, RefreshCw, WalletCards } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";

const money = (v: number) => new Intl.NumberFormat("es-CO", { style: "currency", currency: "COP", maximumFractionDigits: 0 }).format(Number(v) || 0);
const methods = [["cash", "Efectivo"], ["card", "Tarjeta"], ["transfer", "Transferencia"], ["other", "Otro"]];
type Account = { _id: string; orderNumber?: string; reference?: string; clientId?: string; clientName?: string; supplierId?: string; supplierName?: string; amountDue: number; dueDate?: string | null };
type Advance = { _id: string; type: "customer" | "supplier"; partyId: string; partyName: string; originalAmount: number; amountApplied: number; amountAvailable: number; status: string; paymentMethod: string; reference?: string | null; createdAt: string };
type Party = { id: string; name: string };

export default function FinanceOperationsPage() {
  const [tab, setTab] = useState<"customer" | "supplier">("customer");
  const [accounts, setAccounts] = useState<Account[]>([]); const [advances, setAdvances] = useState<Advance[]>([]); const [parties, setParties] = useState<Party[]>([]);
  const [partyId, setPartyId] = useState(""); const [targetId, setTargetId] = useState(""); const [amount, setAmount] = useState(""); const [method, setMethod] = useState("cash"); const [reference, setReference] = useState(""); const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
  async function load() { const [a, av, p] = await Promise.all([fetch(tab === "customer" ? "/api/finance/receivables" : "/api/finance/payables", { credentials: "include", cache: "no-store" }).then(r => r.ok ? r.json() : []), fetch(`/api/finance/advances?type=${tab}`, { credentials: "include", cache: "no-store" }).then(r => r.ok ? r.json() : []), fetch(tab === "customer" ? "/api/clients" : "/api/suppliers", { credentials: "include", cache: "no-store" }).then(r => r.ok ? r.json() : [])]); setAccounts(Array.isArray(a) ? a : []); setAdvances(Array.isArray(av) ? av : []); setParties(Array.isArray(p) ? p : []); }
  useEffect(() => { setPartyId(""); setTargetId(""); void load(); }, [tab]);
  const filtered = partyId ? accounts.filter(a => (tab === "customer" ? a.clientId : a.supplierId) === partyId) : accounts;
  async function postAdvance() { const value = Number(amount); if (!partyId || !Number.isFinite(value) || value <= 0) { setMessage("Selecciona un tercero e indica un valor válido."); return; } setBusy(true); setMessage(""); try { const r = await fetch("/api/finance/advances", { method: "POST", headers: { "Content-Type": "application/json" }, credentials: "include", body: JSON.stringify({ type: tab, partyId, amount: value, paymentMethod: method, reference }) }); const d = await r.json(); if (!r.ok) throw new Error(d.error || "No se pudo registrar"); setAmount(""); setReference(""); setMessage(`Anticipo de ${money(value)} registrado.`); await load(); } catch (e) { setMessage(e instanceof Error ? e.message : "Error al registrar"); } finally { setBusy(false); } }
  async function applyAdvance(a: Advance) { if (!targetId) { setMessage("Selecciona una cuenta destino."); return; } const value = Number(window.prompt(`Disponible: ${money(a.amountAvailable)}\nValor a aplicar:`, String(a.amountAvailable))); if (!Number.isFinite(value) || value <= 0) return; setBusy(true); setMessage(""); try { const r = await fetch("/api/finance/advances", { method: "PATCH", headers: { "Content-Type": "application/json" }, credentials: "include", body: JSON.stringify({ id: a._id, targetId, amount: value }) }); const d = await r.json(); if (!r.ok) throw new Error(d.error || "No se pudo aplicar"); setMessage(`Se aplicaron ${money(value)} correctamente.`); setTargetId(""); await load(); } catch (e) { setMessage(e instanceof Error ? e.message : "Error al aplicar"); } finally { setBusy(false); } }
  async function pay(id: string) { const value = Number(window.prompt("Valor del abono:", "")); if (!Number.isFinite(value) || value <= 0) return; const endpoint = tab === "customer" ? "/api/finance/receivables" : "/api/finance/payables"; setBusy(true); try { const r = await fetch(endpoint, { method: "PATCH", headers: { "Content-Type": "application/json" }, credentials: "include", body: JSON.stringify({ id, amount: value, paymentMethod: method }) }); const d = await r.json(); if (!r.ok) throw new Error(d.error || "No se pudo registrar"); setMessage(`Abono de ${money(value)} registrado.`); await load(); } catch (e) { setMessage(e instanceof Error ? e.message : "Error al registrar abono"); } finally { setBusy(false); } }
  return <main className="space-y-6 p-4 sm:p-6"><header><div className="flex items-center gap-2 text-sm text-muted-foreground"><WalletCards className="h-4 w-4" /> Finanzas / Operaciones</div><h1 className="mt-1 text-2xl font-bold">Cartera, abonos y anticipos</h1><p className="text-sm text-muted-foreground">Opera CxC y CxP sin salir del módulo financiero.</p></header>
    <div className="flex gap-2"><Button variant={tab === "customer" ? "default" : "outline"} onClick={() => setTab("customer")}>CxC · Clientes</Button><Button variant={tab === "supplier" ? "default" : "outline"} onClick={() => setTab("supplier")}>CxP · Proveedores</Button><Button variant="outline" onClick={() => void load()} disabled={busy}><RefreshCw className="mr-2 h-4 w-4" />Actualizar</Button></div>
    <div className="grid gap-6 lg:grid-cols-[380px_1fr]">
      <section className="rounded-2xl border bg-card/80 p-5 shadow-sm"><h2 className="mb-4 font-semibold">Nuevo anticipo</h2><div className="space-y-3"><select value={partyId} onChange={e => { setPartyId(e.target.value); setTargetId(""); }} className="h-10 w-full rounded-lg border bg-background px-3 text-sm"><option value="">Seleccionar {tab === "customer" ? "cliente" : "proveedor"}</option>{parties.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select><Input type="number" min="1" value={amount} onChange={e => setAmount(e.target.value)} placeholder="Valor" /><select value={method} onChange={e => setMethod(e.target.value)} className="h-10 w-full rounded-lg border bg-background px-3 text-sm">{methods.map(([v,l]) => <option key={v} value={v}>{l}</option>)}</select><Input value={reference} onChange={e => setReference(e.target.value)} placeholder="Referencia opcional" /><Button className="w-full bg-amber-600 hover:bg-amber-700" disabled={busy || !partyId || !amount} onClick={() => void postAdvance()}>Registrar anticipo</Button></div></section>
      <section className="rounded-2xl border bg-card/80 p-5 shadow-sm"><h2 className="mb-1 font-semibold">Cuentas abiertas</h2><p className="mb-3 text-xs text-muted-foreground">{filtered.length} cuentas disponibles.</p><select value={targetId} onChange={e => setTargetId(e.target.value)} className="mb-4 h-10 w-full rounded-lg border bg-background px-3 text-sm"><option value="">Seleccionar cuenta para aplicar anticipo</option>{filtered.map(a => <option key={a._id} value={a._id}>{a.orderNumber || a.reference || a._id.slice(-8)} · {money(a.amountDue)}</option>)}</select><div className="space-y-2">{filtered.slice(0, 25).map(a => <div key={a._id} className="flex items-center justify-between gap-3 rounded-xl border p-3"><div className="min-w-0"><p className="font-medium">{a.orderNumber || a.reference || "Cuenta"}</p><p className="text-xs text-muted-foreground">{tab === "customer" ? (a.clientName || "Cliente") : (a.supplierName || "Proveedor")} · vence {a.dueDate ? new Date(a.dueDate).toLocaleDateString("es-CO") : "sin fecha"}</p></div><div className="flex items-center gap-3"><strong>{money(a.amountDue)}</strong><Button size="sm" variant="outline" disabled={busy} onClick={() => void pay(a._id)}>Abonar</Button></div></div>)}{!filtered.length && <p className="py-8 text-center text-sm text-muted-foreground">No hay cuentas abiertas.</p>}</div></section>
    </div>
    <section className="rounded-2xl border bg-card/80 p-5 shadow-sm"><h2 className="mb-4 font-semibold">Anticipos disponibles</h2><div className="space-y-2">{advances.map(a => <div key={a._id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border p-3"><div><p className="font-medium">{a.partyName} <span className="text-xs font-normal text-muted-foreground">· {a.type === "customer" ? "Cliente" : "Proveedor"}</span></p><p className="text-xs text-muted-foreground">{a.reference || "Sin referencia"}</p></div><div className="flex items-center gap-3"><strong>{money(a.amountAvailable)}</strong><Button size="sm" disabled={busy || !targetId || partyId !== a.partyId} onClick={() => void applyAdvance(a)}>Aplicar anticipo</Button></div></div>)}{!advances.length && <p className="py-8 text-center text-sm text-muted-foreground">No hay anticipos disponibles.</p>}</div></section>
    {message && <div className="rounded-xl border bg-muted/40 p-3 text-sm">{message}</div>}
  </main>;
}
