"use client";

import { useState } from "react";
import { Download, Filter, X } from "lucide-react";
import { Button } from "@/components/ui/button";
export type CashFilters = { from: string; to: string; type: string; method: string; source: string };
export default function CashMovementFilters({ filters, onChange, onExport }: { filters: CashFilters; onChange: (filters: CashFilters) => void; onExport: () => void }) {
  const [open, setOpen] = useState(false);
  const update = (key: keyof CashFilters, value: string) => onChange({ ...filters, [key]: value });
  const active = Object.values(filters).filter(Boolean).length;
  return <section className="rounded-2xl border bg-card/80 p-4 shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-2"><Filter className="h-4 w-4 text-amber-600" /><div><h2 className="font-semibold">Filtros de caja</h2><p className="text-xs text-muted-foreground">Consulta movimientos por período, tipo, medio y origen.</p></div></div><div className="flex gap-2"><Button variant="outline" size="sm" onClick={() => setOpen(!open)}><Filter className="mr-2 h-4 w-4" />{open ? "Ocultar" : "Filtrar"}{active > 0 && <span className="ml-1 rounded-full bg-primary px-1.5 text-[10px] text-primary-foreground">{active}</span>}</Button><Button variant="outline" size="sm" onClick={onExport}><Download className="mr-2 h-4 w-4" />CSV</Button></div></div>{open && <div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><label className="text-xs text-muted-foreground">Desde<input type="date" value={filters.from} onChange={e => update("from", e.target.value)} className="mt-1 h-10 w-full rounded-lg border bg-background px-3 text-sm text-foreground" /></label><label className="text-xs text-muted-foreground">Hasta<input type="date" value={filters.to} onChange={e => update("to", e.target.value)} className="mt-1 h-10 w-full rounded-lg border bg-background px-3 text-sm text-foreground" /></label><label className="text-xs text-muted-foreground">Tipo<select value={filters.type} onChange={e => update("type", e.target.value)} className="mt-1 h-10 w-full rounded-lg border bg-background px-3 text-sm"><option value="">Todos</option><option value="income">Ingresos</option><option value="expense">Egresos</option></select></label><label className="text-xs text-muted-foreground">Medio<select value={filters.method} onChange={e => update("method", e.target.value)} className="mt-1 h-10 w-full rounded-lg border bg-background px-3 text-sm"><option value="">Todos</option><option value="cash">Efectivo</option><option value="card">Tarjeta</option><option value="transfer">Transferencia</option><option value="other">Otro</option></select></label><label className="text-xs text-muted-foreground">Origen<select value={filters.source} onChange={e => update("source", e.target.value)} className="mt-1 h-10 w-full rounded-lg border bg-background px-3 text-sm"><option value="">Todos</option><option value="sale">Venta</option><option value="repair">Reparación</option><option value="manual">Manual</option><option value="refund">Reembolso</option></select></label>{active > 0 && <Button variant="ghost" size="sm" className="sm:col-span-2 lg:col-span-5 justify-self-start" onClick={() => onChange({ from: "", to: "", type: "", method: "", source: "" })}><X className="mr-2 h-4 w-4" />Limpiar filtros</Button>}</div>}</section>;
}
