"use client";

import { useEffect, useRef, useState } from "react";
import { ArrowLeft, ClipboardCheck, Package, UserRound, Wrench, CreditCard, Camera, Trash2, X } from "lucide-react";
import Link from "next/link";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";

const statuses = { received: "Recibido", diagnosis: "Diagnóstico", awaiting_approval: "Esperando aprobación", repairing: "En reparación", ready: "Listo", delivered: "Entregado", cancelled: "Cancelado" } as const;
type Status = keyof typeof statuses;
type Photo = { id: string; url: string; filename?: string; category?: string; uploadedAt?: string };
type Part = { id: string; productId: string; name: string; sku?: string; quantity: number; unitPrice: number; subtotal: number; consumed: boolean; warehouseId?: string; warehouseName?: string };
type Payment = { id: string; amount: number; paymentMethod: string; at: string };
type Product = { id: string; name: string; sku: string; price: number; quantity: number };
type Warehouse = { id: string; name: string; address?: string | null; type?: string | null; status: boolean };
type Order = { _id: string; orderNumber: string; customer: string; phone: string; device: string; imei?: string; serial?: string; issue: string; status: Status; diagnosis?: string; technicianNotes?: string; technicianId?: string; labor?: number; discount?: number; parts?: Part[]; payments?: Payment[]; photos?: Photo[]; total: number; paid: number; balance: number };

function compressImage(file: File): Promise<string> {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onerror = () => reject(new Error("No se pudo leer la fotografía"));
    reader.onload = () => {
      const image = new Image();
      image.onerror = () => reject(new Error("La fotografía no es válida"));
      image.onload = () => {
        const max = 1600, scale = Math.min(1, max / Math.max(image.width, image.height));
        const canvas = document.createElement("canvas");
        canvas.width = Math.max(1, Math.round(image.width * scale)); canvas.height = Math.max(1, Math.round(image.height * scale));
        const ctx = canvas.getContext("2d"); if (!ctx) return reject(new Error("No se pudo procesar la fotografía"));
        ctx.drawImage(image, 0, 0, canvas.width, canvas.height);
        resolve(canvas.toDataURL("image/jpeg", 0.78));
      };
      image.src = String(reader.result);
    };
    reader.readAsDataURL(file);
  });
}

export default function ServiceOrderDetail({ orderId }: { orderId: string }) {
  const [order, setOrder] = useState<Order | null>(null), [products, setProducts] = useState<Product[]>([]), [warehouses, setWarehouses] = useState<Warehouse[]>([]), [diagnosis, setDiagnosis] = useState(""), [technicianNotes, setTechnicianNotes] = useState(""), [status, setStatus] = useState<Status>("received"), [technicianId, setTechnicianId] = useState(""), [labor, setLabor] = useState(""), [discount, setDiscount] = useState(""), [partProductId, setPartProductId] = useState(""), [partQty, setPartQty] = useState("1"), [consumePartId, setConsumePartId] = useState(""), [warehouseId, setWarehouseId] = useState(""), [paymentAmount, setPaymentAmount] = useState(""), [paymentMethod, setPaymentMethod] = useState("efectivo"), [saving, setSaving] = useState(false), [photoBusy, setPhotoBusy] = useState(false), [preview, setPreview] = useState<Photo | null>(null), [message, setMessage] = useState("");
  const photoInput = useRef<HTMLInputElement>(null);

  const load = async () => { try { const [orderResponse, productsResponse, warehousesResponse] = await Promise.all([fetch(`/api/service-orders?search=${encodeURIComponent(orderId)}`, { cache: "no-store" }), fetch("/api/products", { cache: "no-store" }), fetch("/api/warehouses", { cache: "no-store" })]); const data = await orderResponse.json(); if (!orderResponse.ok) throw new Error(data.error || "No se pudo cargar la orden"); const found = data.orders?.find((item: Order) => item._id === orderId || item.orderNumber === orderId); if (!found) throw new Error("Orden no encontrada"); setOrder(found); setDiagnosis(found.diagnosis || ""); setTechnicianNotes(found.technicianNotes || ""); setTechnicianId(found.technicianId || ""); setStatus(found.status); setLabor(String(found.labor || "")); setDiscount(String(found.discount || "")); if (productsResponse.ok) { const productData = await productsResponse.json(); setProducts(Array.isArray(productData) ? productData.filter((p: Product) => Number(p.quantity) > 0) : []); } if (warehousesResponse.ok) { const warehouseData = await warehousesResponse.json(); setWarehouses(Array.isArray(warehouseData) ? warehouseData.filter((w: Warehouse) => w.status !== false) : []); } } catch (error) { setMessage(error instanceof Error ? error.message : "No se pudo cargar la orden"); } };
  useEffect(() => { void load(); }, [orderId]);
  const save = async (extra: Record<string, unknown> = {}) => { if (!order) return; setSaving(true); setMessage(""); try { const response = await fetch("/api/service-orders", { method: "PUT", headers: { "content-type": "application/json" }, body: JSON.stringify({ id: order._id, diagnosis, technicianNotes, technicianId, status, ...extra }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || "No se pudo guardar"); setOrder(data); setMessage("Guardado correctamente."); } catch (error) { setMessage(error instanceof Error ? error.message : "No se pudo guardar"); } finally { setSaving(false); } };
  const action = async (payload: Record<string, unknown>) => { if (!order) return; setSaving(true); setMessage(""); try { const response = await fetch("/api/service-orders", { method: "PUT", headers: { "content-type": "application/json" }, body: JSON.stringify({ id: order._id, ...payload }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || "No se pudo completar la operación"); setOrder(data); if (payload.action === "consume_part") { setConsumePartId(""); setWarehouseId(""); } setMessage("Operación completada correctamente."); } catch (error) { setMessage(error instanceof Error ? error.message : "Error en la operación"); } finally { setSaving(false); } };
  const uploadPhoto = async (file: File) => { if (!order || photoBusy) return; if (!file.type.startsWith("image/")) { setMessage("Selecciona una imagen válida."); return; } setPhotoBusy(true); setMessage(""); try { const dataUrl = await compressImage(file); const response = await fetch("/api/service-orders/photos", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ orderId: order._id, dataUrl, filename: file.name }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || "No se pudo guardar la fotografía"); setOrder(prev => prev ? { ...prev, photos: [...(prev.photos || []), data.photo] } : prev); setMessage("Fotografía de ingreso guardada."); } catch (error) { setMessage(error instanceof Error ? error.message : "No se pudo guardar la fotografía"); } finally { setPhotoBusy(false); if (photoInput.current) photoInput.current.value = ""; } };
  const removePhoto = async (photoId: string) => { if (!order) return; setPhotoBusy(true); try { const response = await fetch("/api/service-orders/photos", { method: "DELETE", headers: { "content-type": "application/json" }, body: JSON.stringify({ orderId: order._id, photoId }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || "No se pudo eliminar"); setOrder(prev => prev ? { ...prev, photos: (prev.photos || []).filter(photo => photo.id !== photoId) } : prev); setPreview(null); setMessage("Fotografía eliminada."); } catch (error) { setMessage(error instanceof Error ? error.message : "No se pudo eliminar la fotografía"); } finally { setPhotoBusy(false); } };
  if (!order) return <main className="p-6"><Link href="/admin/service-orders"><Button variant="outline"><ArrowLeft className="mr-2 h-4 w-4" />Volver</Button></Link><div className="mt-6 rounded-lg border p-6 text-sm text-muted-foreground">{message || "Cargando orden..."}</div></main>;
  const money = (n: number) => `$${Number(n || 0).toLocaleString("es-CO")}`;
  return <main className="space-y-6 p-2 sm:p-4">
    <div className="flex flex-wrap items-center justify-between gap-3"><Link href="/admin/service-orders"><Button variant="outline"><ArrowLeft className="mr-2 h-4 w-4" />Servicio técnico</Button></Link><Button onClick={() => void save()} disabled={saving}>{saving ? "Guardando..." : "Guardar cambios"}</Button></div>
    <div><h1 className="text-2xl font-semibold">{order.orderNumber}</h1><p className="text-sm text-muted-foreground">Detalle de reparación · {statuses[order.status]}</p></div>
    <Card><CardHeader><CardTitle className="flex items-center gap-2"><Camera className="h-5 w-5" />Evidencia fotográfica de ingreso</CardTitle></CardHeader><CardContent className="space-y-4"><input ref={photoInput} type="file" accept="image/*" capture="environment" className="hidden" onChange={e => { const file = e.target.files?.[0]; if (file) void uploadPhoto(file); }} /><div className="flex flex-wrap gap-2"><Button type="button" disabled={photoBusy || order.status === "delivered" || order.status === "cancelled"} onClick={() => photoInput.current?.click()}><Camera className="mr-2 h-4 w-4" />{photoBusy ? "Procesando..." : "Tomar / cargar foto"}</Button><span className="self-center text-xs text-muted-foreground">Hasta 12 fotos · quedan registradas como evidencia de ingreso</span></div>{(order.photos || []).length === 0 ? <div className="rounded-lg border border-dashed p-8 text-center text-sm text-muted-foreground">Aún no hay fotografías. Toma fotos de pantalla, marco, tapas, cámaras, conectores y cualquier daño visible antes de reparar.</div> : <div className="grid grid-cols-2 gap-3 sm:grid-cols-3 md:grid-cols-4">{(order.photos || []).map(photo => <div key={photo.id} className="group relative overflow-hidden rounded-lg border"><button type="button" className="block w-full" onClick={() => setPreview(photo)}><img src={photo.url} alt={photo.filename || "Evidencia de ingreso"} className="aspect-square w-full object-cover" /></button>{order.status !== "delivered" && order.status !== "cancelled" && <Button type="button" size="icon" variant="destructive" className="absolute right-2 top-2 opacity-90" disabled={photoBusy} onClick={() => void removePhoto(photo.id)} aria-label="Eliminar fotografía"><Trash2 className="h-4 w-4" /></Button>}<div className="bg-background/90 px-2 py-1 text-[11px]">Ingreso · {photo.uploadedAt ? new Date(photo.uploadedAt).toLocaleString("es-CO") : ""}</div></div>)}</div>}</CardContent></Card>
    <div className="grid gap-4 md:grid-cols-2"><Card><CardHeader><CardTitle className="flex items-center gap-2"><UserRound className="h-5 w-5" />Cliente y equipo</CardTitle></CardHeader><CardContent className="space-y-3 text-sm"><p><b>Cliente:</b> {order.customer}</p><p><b>Teléfono:</b> {order.phone}</p><p><b>Equipo:</b> {order.device}</p><p><b>IMEI:</b> {order.imei || "—"}</p><p><b>Serial:</b> {order.serial || "—"}</p><p><b>Falla:</b> {order.issue}</p></CardContent></Card><Card><CardHeader><CardTitle className="flex items-center gap-2"><Wrench className="h-5 w-5" />Estado y técnico</CardTitle></CardHeader><CardContent className="space-y-4"><div className="space-y-2"><Label>Estado</Label><Select value={status} onValueChange={value => setStatus(value as Status)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{Object.entries(statuses).map(([key, label]) => <SelectItem key={key} value={key}>{label}</SelectItem>)}</SelectContent></Select></div><div className="space-y-2"><Label>Técnico / identificación</Label><Input value={technicianId} onChange={e => setTechnicianId(e.target.value)} placeholder="Nombre o ID del técnico" /></div><div className="space-y-2"><Label>Notas de reparación</Label><Input value={technicianNotes} onChange={e => setTechnicianNotes(e.target.value)} placeholder="Trabajo realizado" /></div></CardContent></Card></div>
    <Card><CardHeader><CardTitle className="flex items-center gap-2"><ClipboardCheck className="h-5 w-5" />Diagnóstico</CardTitle></CardHeader><CardContent><Textarea value={diagnosis} onChange={e => setDiagnosis(e.target.value)} placeholder="Resultado de la revisión técnica" rows={5} /></CardContent></Card>
    <Card><CardHeader><CardTitle>Presupuesto</CardTitle></CardHeader><CardContent className="space-y-4"><div className="grid gap-3 md:grid-cols-2"><div><Label>Mano de obra</Label><Input type="number" min="0" value={labor} onChange={e => setLabor(e.target.value)} /></div><div><Label>Descuento</Label><Input type="number" min="0" value={discount} onChange={e => setDiscount(e.target.value)} /></div></div><div className="flex gap-2"><Button variant="outline" disabled={saving} onClick={() => void action({ action: "set_labor", amount: Number(labor || 0) })}>Guardar mano de obra</Button><Button variant="outline" disabled={saving} onClick={() => void action({ action: "set_discount", amount: Number(discount || 0) })}>Guardar descuento</Button></div></CardContent></Card>
    <Card><CardHeader><CardTitle className="flex items-center gap-2"><Package className="h-5 w-5" />Repuestos del inventario</CardTitle></CardHeader><CardContent className="space-y-4"><div className="grid gap-3 md:grid-cols-[1fr_140px_auto]"><Select value={partProductId} onValueChange={setPartProductId}><SelectTrigger><SelectValue placeholder="Selecciona un producto" /></SelectTrigger><SelectContent>{products.map(product => <SelectItem key={product.id} value={product.id}>{product.name} · {product.sku} · stock {product.quantity}</SelectItem>)}</SelectContent></Select><Input type="number" min="1" value={partQty} onChange={e => setPartQty(e.target.value)} placeholder="Cantidad" /><Button disabled={saving || !partProductId} onClick={() => void action({ action: "add_part", productId: partProductId, quantity: Number(partQty) })}>Agregar repuesto</Button></div>{(order.parts || []).map(part => <div key={part.id} className="rounded-lg border p-3 text-sm"><div className="flex flex-wrap justify-between gap-2"><span><b>{part.name}</b> · {part.sku || part.productId} · x{part.quantity}</span><span>{money(part.subtotal)}</span></div>{part.consumed ? <p className="mt-2 text-xs text-muted-foreground">Consumido de inventario · bodega {part.warehouseName || part.warehouseId || "—"}</p> : <div className="mt-3 grid gap-2 sm:grid-cols-[1fr_auto] sm:items-end"><div className="space-y-2"><Label>Bodega de salida</Label><Select value={consumePartId === part.id ? warehouseId : ""} onValueChange={value => { setConsumePartId(part.id); setWarehouseId(value); }}><SelectTrigger><SelectValue placeholder={warehouses.length ? "Selecciona la bodega" : "No hay bodegas activas"} /></SelectTrigger><SelectContent>{warehouses.map(warehouse => <SelectItem key={warehouse.id} value={warehouse.id}>{warehouse.name}{warehouse.type ? ` · ${warehouse.type}` : ""}</SelectItem>)}</SelectContent></Select></div><Button variant="outline" disabled={saving || consumePartId !== part.id || !warehouseId} onClick={() => void action({ action: "consume_part", partId: part.id, warehouseId })}>Descontar inventario</Button></div>}</div>)}</CardContent></Card>
    <Card><CardHeader><CardTitle className="flex items-center gap-2"><CreditCard className="h-5 w-5" />Pagos</CardTitle></CardHeader><CardContent className="space-y-4"><div className="grid gap-3 md:grid-cols-3"><Input type="number" min="0" placeholder="Valor del abono" value={paymentAmount} onChange={e => setPaymentAmount(e.target.value)} /><Select value={paymentMethod} onValueChange={setPaymentMethod}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{["efectivo", "transferencia", "tarjeta", "datafono", "otro"].map(method => <SelectItem key={method} value={method}>{method}</SelectItem>)}</SelectContent></Select><Button disabled={saving || !paymentAmount} onClick={() => void action({ action: "payment", amount: Number(paymentAmount), paymentMethod })}>Registrar abono</Button></div>{(order.payments || []).map(payment => <p key={payment.id} className="text-sm">{money(payment.amount)} · {payment.paymentMethod}</p>)}</CardContent></Card>
    <Card><CardHeader><CardTitle>Resumen económico</CardTitle></CardHeader><CardContent className="grid gap-3 md:grid-cols-3 text-sm"><p>Total<br /><b>{money(order.total)}</b></p><p>Pagado<br /><b>{money(order.paid)}</b></p><p>Saldo<br /><b>{money(order.balance)}</b></p></CardContent></Card>
    {message && <div className="rounded-lg border p-3 text-sm">{message}</div>}
    {preview && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/80 p-4" role="dialog" aria-modal="true" onClick={() => setPreview(null)}><div className="relative max-h-[95vh] max-w-5xl" onClick={e => e.stopPropagation()}><Button type="button" variant="secondary" size="icon" className="absolute right-2 top-2 z-10" onClick={() => setPreview(null)}><X className="h-4 w-4" /></Button><img src={preview.url} alt={preview.filename || "Evidencia de ingreso"} className="max-h-[90vh] max-w-full rounded-lg object-contain" /></div></div>}
  </main>;
}
