"use client";

import { useEffect, useMemo, useState } from "react";
import { Archive, Calculator, Pencil, Plus, Search, ShieldCheck, Smartphone, X } from "lucide-react";

type Device = { id: string; name: string; brand: string; model: string; imei1: string; imei2: string; serial: string; clientName: string; status: string; purchasePrice: number; repairCost: number; salePrice: number; investment: number; profit: number; margin: number; warrantyDays: number; warrantyExpiresAt: string | null; serviceOrderId: string | null; saleOrderId: string | null; notes: string; passcodeSet: boolean; };
type Form = Omit<Device, "id" | "investment" | "profit" | "margin" | "passcodeSet"> & { phonePasscode: string };
const empty: Form = { name: "", brand: "", model: "", imei1: "", imei2: "", serial: "", clientName: "", status: "available", purchasePrice: 0, repairCost: 0, salePrice: 0, warrantyDays: 0, warrantyExpiresAt: null, serviceOrderId: null, saleOrderId: null, notes: "", phonePasscode: "" };
const money = (n: number) => new Intl.NumberFormat("es-CO", { style: "currency", currency: "COP", maximumFractionDigits: 0 }).format(n);

export default function DevicesPage() {
  const [devices, setDevices] = useState<Device[]>([]); const [q, setQ] = useState(""); const [open, setOpen] = useState(false); const [editing, setEditing] = useState<Device | null>(null); const [form, setForm] = useState<Form>(empty); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  async function load() { setLoading(true); try { const r = await fetch(`/api/devices?search=${encodeURIComponent(q)}`, { cache: "no-store" }); const d = await r.json(); if (!r.ok) throw new Error(d.error); setDevices(d.devices ?? []); } catch (e) { setError(e instanceof Error ? e.message : "No se pudieron cargar los equipos"); } finally { setLoading(false); } }
  useEffect(() => { const t = setTimeout(load, 180); return () => clearTimeout(t); }, [q]);
  const stats = useMemo(() => ({ total: devices.length, available: devices.filter(d => d.status === "available").length, repair: devices.filter(d => d.status === "in_repair").length, profit: devices.reduce((s, d) => s + Number(d.profit || 0), 0) }), [devices]);
  function edit(d: Device) { setEditing(d); setForm({ ...d, warrantyExpiresAt: null, serviceOrderId: d.serviceOrderId, saleOrderId: d.saleOrderId, phonePasscode: "" }); setError(""); setOpen(true); }
  function create() { setEditing(null); setForm(empty); setError(""); setOpen(true); }
  async function save() { setSaving(true); setError(""); try { const r = await fetch("/api/devices", { method: editing ? "PUT" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(editing ? { ...form, id: editing.id } : form) }); const d = await r.json(); if (!r.ok) throw new Error(d.error); setOpen(false); await load(); } catch (e) { setError(e instanceof Error ? e.message : "No se pudo guardar"); } finally { setSaving(false); } }
  async function archive(d: Device) { if (!confirm(`¿Archivar ${d.name}?`)) return; const r = await fetch(`/api/devices?id=${d.id}`, { method: "DELETE" }); if (r.ok) load(); else { const x = await r.json(); setError(x.error || "No se pudo archivar"); } }
  const field = (key: keyof Form, label: string, type = "text", extra = "") => <label className={`block ${extra}`}><span className="mb-1.5 block text-xs font-medium text-muted-foreground">{label}</span><input type={type} value={String(form[key] ?? "")} onChange={e => setForm(f => ({ ...f, [key]: type === "number" ? Number(e.target.value) : e.target.value }))} className="h-10 w-full rounded-xl border border-gray-200 bg-white/70 px-3 text-sm outline-none focus:border-violet-400 focus:ring-2 focus:ring-violet-500/15 dark:border-white/10 dark:bg-white/[0.06]" /></label>;
  return <div className="min-h-screen p-4 sm:p-6 lg:p-8"><div className="mx-auto max-w-7xl space-y-6">
    <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex items-center gap-2"><Smartphone className="h-5 w-5 text-violet-500" /><h1 className="text-xl font-semibold">Equipos DarkPhone</h1></div><p className="mt-1 text-sm text-muted-foreground">IMEI, seriales, claves, garantías y rentabilidad por equipo.</p></div><button onClick={create} className="inline-flex h-10 items-center justify-center gap-2 rounded-xl bg-primary px-4 text-sm font-medium text-primary-foreground"><Plus className="h-4 w-4" />Registrar equipo</button></div>
    <div className="grid grid-cols-2 gap-3 lg:grid-cols-4"><Metric title="Equipos" value={String(stats.total)} /><Metric title="Disponibles" value={String(stats.available)} /><Metric title="En reparación" value={String(stats.repair)} /><Metric title="Utilidad registrada" value={money(stats.profit)} /></div>
    <div className="rounded-2xl border border-white/10 bg-white/70 p-4 shadow-sm backdrop-blur-xl dark:bg-white/[0.05]"><div className="relative"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" /><input value={q} onChange={e => setQ(e.target.value)} placeholder="Buscar nombre, modelo, IMEI, serial o cliente..." className="h-11 w-full rounded-xl border border-gray-200 bg-white/80 pl-9 pr-3 text-sm outline-none focus:border-violet-400 dark:border-white/10 dark:bg-white/[0.06]" /></div></div>
    {error && <div className="rounded-xl border border-destructive/30 bg-destructive/5 p-3 text-sm text-destructive">{error}</div>}
    <div className="overflow-hidden rounded-2xl border border-gray-200/70 bg-white/70 shadow-sm dark:border-white/10 dark:bg-white/[0.04]"><div className="overflow-x-auto"><table className="w-full min-w-[980px] text-sm"><thead><tr className="border-b bg-muted/30 text-left text-muted-foreground"><th className="px-4 py-3">Equipo</th><th className="px-4 py-3">IMEI / Serial</th><th className="px-4 py-3">Cliente</th><th className="px-4 py-3">Inversión</th><th className="px-4 py-3">Venta</th><th className="px-4 py-3">Utilidad</th><th className="px-4 py-3">Estado</th><th className="px-4 py-3 text-right">Acciones</th></tr></thead><tbody>{loading ? <tr><td colSpan={8} className="px-4 py-14 text-center text-muted-foreground">Cargando equipos...</td></tr> : devices.length === 0 ? <tr><td colSpan={8} className="px-4 py-14 text-center text-muted-foreground">No hay equipos registrados.</td></tr> : devices.map(d => <tr key={d.id} className="border-b last:border-0 hover:bg-muted/20"><td className="px-4 py-4"><div className="font-medium">{d.name}</div><div className="text-xs text-muted-foreground">{d.brand} {d.model}{d.passcodeSet ? " · 🔐 clave" : ""}</div></td><td className="px-4 py-4"><div>{d.imei1 || d.imei2 || "—"}</div><div className="text-xs text-muted-foreground">{d.serial || "Sin serial"}</div></td><td className="px-4 py-4">{d.clientName || "—"}</td><td className="px-4 py-4">{money(d.investment)}</td><td className="px-4 py-4">{money(d.salePrice)}</td><td className={`px-4 py-4 font-medium ${d.profit >= 0 ? "text-emerald-600" : "text-red-600"}`}>{money(d.profit)}<div className="text-xs font-normal text-muted-foreground">{Number(d.margin).toFixed(1)}%</div></td><td className="px-4 py-4"><span className="rounded-full bg-muted px-2.5 py-1 text-xs">{d.status === "in_repair" ? "En reparación" : d.status === "sold" ? "Vendido" : d.status === "archived" ? "Archivado" : "Disponible"}</span>{d.warrantyExpiresAt && <div className="mt-1 text-xs text-muted-foreground">Garantía: {new Date(d.warrantyExpiresAt).toLocaleDateString("es-CO")}</div>}</td><td className="px-4 py-4 text-right"><button onClick={() => edit(d)} className="mr-1 rounded-lg p-2 hover:bg-muted" title="Editar"><Pencil className="h-4 w-4" /></button><button onClick={() => archive(d)} className="rounded-lg p-2 text-muted-foreground hover:bg-muted" title="Archivar"><Archive className="h-4 w-4" /></button></td></tr>)}</tbody></table></div></div>
    {open && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4"><div className="max-h-[92vh] w-full max-w-3xl overflow-y-auto rounded-2xl border bg-background p-5 shadow-2xl"><div className="mb-5 flex items-center justify-between"><div><h2 className="text-lg font-semibold">{editing ? "Editar equipo" : "Registrar equipo"}</h2><p className="text-xs text-muted-foreground">Los IMEI/seriales se protegen contra duplicados por cuenta.</p></div><button onClick={() => setOpen(false)}><X className="h-5 w-5" /></button></div><div className="grid gap-4 sm:grid-cols-2">{field("name", "Nombre interno *")}{field("brand", "Marca")}{field("model", "Modelo *")}{field("clientName", "Cliente")}{field("imei1", "IMEI 1", "text")}{field("imei2", "IMEI 2", "text")}{field("serial", "Serial")}{field("phonePasscode", "Clave del teléfono (opcional)", "password")}{field("purchasePrice", "Precio de compra", "number")}{field("repairCost", "Costo de reparación", "number")}{field("salePrice", "Precio de venta", "number")}{field("warrantyDays", "Garantía (días)", "number")}</div><div className="mt-4 grid gap-4 sm:grid-cols-2"><label className="block"><span className="mb-1.5 block text-xs font-medium text-muted-foreground">Estado</span><select value={form.status} onChange={e => setForm(f => ({ ...f, status: e.target.value }))} className="h-10 w-full rounded-xl border bg-background px-3 text-sm"><option value="available">Disponible</option><option value="in_repair">En reparación</option><option value="sold">Vendido</option></select></label>{field("serviceOrderId", "ID orden de servicio (opcional)")}</div>{field("notes", "Notas", "text", "mt-4 sm:col-span-2")}<div className="mt-5 flex items-center justify-end gap-2"><button onClick={() => setOpen(false)} className="rounded-xl border px-4 py-2 text-sm">Cancelar</button><button disabled={saving} onClick={save} className="inline-flex items-center gap-2 rounded-xl bg-primary px-4 py-2 text-sm font-medium text-primary-foreground disabled:opacity-50">{saving ? "Guardando..." : <><ShieldCheck className="h-4 w-4" />Guardar equipo</>}</button></div></div></div>}
  </div></div>;
}
function Metric({ title, value }: { title: string; value: string }) { return <div className="rounded-2xl border bg-background/70 p-4"><div className="text-xs text-muted-foreground">{title}</div><div className="mt-1 flex items-center gap-2 text-lg font-semibold"><Calculator className="h-4 w-4 text-violet-500" />{value}</div></div>; }
