"use client";
import { useEffect, useState } from "react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";

type Quote = { _id: string; quoteNumber: string; customerName: string; total: number; status: string; createdAt: string };
export default function QuotesPage() {
 const [quotes,setQuotes]=useState<Quote[]>([]),[name,setName]=useState(""),[phone,setPhone]=useState(""),[email,setEmail]=useState(""),[item,setItem]=useState(""),[price,setPrice]=useState(""),[qty,setQty]=useState("1"),[discount,setDiscount]=useState(""),[notes,setNotes]=useState(""),[validUntil,setValidUntil]=useState(""),[message,setMessage]=useState("");
 const load=async()=>{const r=await fetch("/api/quotes",{cache:"no-store"});const d=await r.json();if(r.ok)setQuotes(d.quotes||[]);}; useEffect(()=>{void load()},[]);
 const create=async()=>{setMessage("");const r=await fetch("/api/quotes",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({customerName:name,customerPhone:phone,customerEmail:email,notes,validUntil,discount:Number(discount||0),items:[{name:item,quantity:Number(qty||1),unitPrice:Number(price||0)}]})});const d=await r.json();if(!r.ok){setMessage(d.error||"No se pudo crear");return;}setMessage(`Cotización ${d.quoteNumber} creada correctamente.`);setName("");setPhone("");setEmail("");setItem("");setPrice("");setQty("1");setDiscount("");setNotes("");setValidUntil("");void load();};
 return <main className="space-y-6 p-4 sm:p-6"><div><h1 className="text-2xl font-semibold">Cotizaciones</h1><p className="text-sm text-muted-foreground">Crea presupuestos y conviértelos después en una venta u orden de servicio.</p></div>
 <Card><CardHeader><CardTitle>Nueva cotización</CardTitle></CardHeader><CardContent className="grid gap-4 md:grid-cols-2"><div><Label>Cliente</Label><Input value={name} onChange={e=>setName(e.target.value)} placeholder="Nombre del cliente"/></div><div><Label>Teléfono</Label><Input value={phone} onChange={e=>setPhone(e.target.value)}/></div><div><Label>Correo</Label><Input value={email} onChange={e=>setEmail(e.target.value)}/></div><div><Label>Válida hasta</Label><Input type="date" value={validUntil} onChange={e=>setValidUntil(e.target.value)}/></div><div className="md:col-span-2"><Label>Producto / servicio</Label><Input value={item} onChange={e=>setItem(e.target.value)} placeholder="Ej. Cambio de pantalla iPhone 15 Pro Max"/></div><div><Label>Precio unitario</Label><Input type="number" min="0" value={price} onChange={e=>setPrice(e.target.value)}/></div><div><Label>Cantidad</Label><Input type="number" min="1" value={qty} onChange={e=>setQty(e.target.value)}/></div><div><Label>Descuento</Label><Input type="number" min="0" value={discount} onChange={e=>setDiscount(e.target.value)}/></div><div><Label>Notas</Label><Textarea value={notes} onChange={e=>setNotes(e.target.value)}/></div><div className="md:col-span-2 flex items-center justify-between gap-3"><span className="text-sm text-muted-foreground">La cotización queda en estado borrador.</span><Button onClick={()=>void create()} disabled={!name||!item||!price}>Crear cotización</Button></div>{message&&<div className="md:col-span-2 rounded-md border p-3 text-sm">{message}</div>}</CardContent></Card>
 <Card><CardHeader><CardTitle>Historial</CardTitle></CardHeader><CardContent>{quotes.length===0?<p className="text-sm text-muted-foreground">No hay cotizaciones todavía.</p>:<div className="space-y-2">{quotes.map(q=><div key={q._id} className="flex flex-wrap items-center justify-between gap-3 rounded-lg border p-3"><div><b>{q.quoteNumber}</b><div className="text-sm text-muted-foreground">{q.customerName} · {q.status}</div></div><b>${Number(q.total||0).toLocaleString("es-CO")}</b></div>)}</div>}</CardContent></Card>
 </main>;
}
