"use client";

import { useEffect, useMemo, useState } from "react";
import { ArrowDownCircle, ArrowUpCircle, Banknote, Plus, Wallet, Ban, Calculator, RefreshCw } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { PageSectionHeader } from "@/components/shared/PageSectionHeader";
import CashInvoicePayments from "@/components/admin/CashInvoicePayments";
import CashMovementFilters, { type CashFilters } from "@/components/admin/CashMovementFilters";

const money = (value: number) => new Intl.NumberFormat("es-CO", { style: "currency", currency: "COP", maximumFractionDigits: 0 }).format(value || 0);
const methodLabel: Record<string, string> = { cash: "Efectivo", card: "Tarjeta", transfer: "Transferencia", other: "Otro" };
const sourceLabel: Record<string, string> = { sale: "Venta", repair: "Reparación", manual: "Manual", refund: "Reembolso" };
type Movement = { _id: string; type: "income" | "expense"; amount: number; paymentMethod: string; source: string; description: string; createdAt: string; status?: "active" | "voided"; voidReason?: string };
type Data = { movements: Movement[]; summary: { income: number; expense: number; balance: number; bySource: Record<string, number> } };

export default function CashPage() {
  const [data, setData] = useState<Data>({ movements: [], summary: { income: 0, expense: 0, balance: 0, bySource: {} } });
  const [filters, setFilters] = useState<CashFilters>({ from: "", to: "", type: "", method: "", source: "" });
  const [type, setType] = useState<"income" | "expense">("expense"); const [amount, setAmount] = useState(""); const [paymentMethod, setPaymentMethod] = useState("cash"); const [description, setDescription] = useState(""); const [saving, setSaving] = useState(false); const [message, setMessage] = useState(""); const [voidingId, setVoidingId] = useState<string | null>(null);
  async function load() { const p = new URLSearchParams(); Object.entries(filters).forEach(([k,v]) => { if (v) p.set(k,v); }); const response = await fetch(`/api/cash${p.toString() ? `?${p}` : ""}`, { credentials: "include", cache: "no-store" }); if (response.ok) setData(await response.json()); }
  useEffect(() => { void load(); }, [filters]);
  async function saveMovement() { setSaving(true); setMessage(""); try { const r = await fetch("/api/cash", { method: "POST", headers: { "Content-Type": "application/json" }, credentials: "include", body: JSON.stringify({ type, amount: Number(amount), paymentMethod, description }) }); const result = await r.json(); if (!r.ok) throw new Error(result.error || "No se pudo guardar"); setAmount(""); setDescription(""); setMessage("Movimiento registrado correctamente."); await load(); } catch (e) { setMessage(e instanceof Error ? e.message : "Error al registrar movimiento"); } finally { setSaving(false); } }
  async function voidMovement(m: Movement) { if (m.status === "voided") return; if (!window.confirm(`¿Anular este movimiento de ${money(Number(m.amount))}?`)) return; const reason = window.prompt("Motivo de la anulación:", "Movimiento registrado por error")?.trim(); if (reason === null) return; setVoidingId(m._id); setMessage(""); try { const r = await fetch("/api/cash", { method: "DELETE", headers: { "Content-Type": "application/json" }, credentials: "include", body: JSON.stringify({ id: m._id, reason: reason || "Movimiento anulado manualmente" }) }); const result = await r.json(); if (!r.ok) throw new Error(result.error || "No se pudo anular"); setMessage("Movimiento anulado correctamente."); await load(); } catch (e) { setMessage(e instanceof Error ? e.message : "Error al anular movimiento"); } finally { setVoidingId(null); } }
  const active = useMemo(() => data.movements.filter(m => m.status !== "voided"), [data.movements]);
  function exportCsv() { const rows = [["Fecha","Tipo","Origen","Medio","Descripción","Valor","Estado"], ...data.movements.map(m => [new Date(m.createdAt).toLocaleString("es-CO"), m.type === "income" ? "Ingreso" : "Egreso", sourceLabel[m.source] || m.source, methodLabel[m.paymentMethod] || m.paymentMethod, m.description || "", String(m.amount), m.status === "voided" ? "Anulado" : "Activo"])]; const csv = rows.map(r => r.map(v => `"${String(v).replaceAll('"','""')}"`).join(",")).join("\n"); const blob = new Blob(["\ufeff" + csv], { type: "text/csv;charset=utf-8" }); const url = URL.createObjectURL(blob); const a = document.createElement("a"); a.href = url; a.download = `caja-${new Date().toISOString().slice(0,10)}.csv`; a.click(); URL.revokeObjectURL(url); }
  const cards = [{ label: "Saldo total", value: data.summary.balance, icon: Wallet }, { label: "Ingresos", value: data.summary.income, icon: ArrowUpCircle }, { label: "Egresos", value: data.summary.expense, icon: ArrowDownCircle }];
  return <main className="space-y-6 p-4 sm:p-6">
    <PageSectionHeader title="Caja" description="Control de ingresos, egresos y movimientos de dinero." tone="amber" icon={Banknote} />
    <div className="grid gap-4 md:grid-cols-3">{cards.map(({ label, value, icon: Icon }) => <div key={label} className="rounded-2xl border bg-card/80 p-5 shadow-sm"><div className="mb-3 flex items-center gap-2 text-sm text-muted-foreground"><Icon className="h-4 w-4" />{label}</div><p className="text-2xl font-bold">{money(value)}</p></div>)}</div>
    <CashInvoicePayments />
    <CashMovementFilters filters={filters} onChange={setFilters} onExport={exportCsv} />
    <section className="rounded-2xl border bg-card/80 p-5 shadow-sm"><div className="mb-4 flex items-center gap-2"><Calculator className="h-5 w-5 text-amber-600" /><h2 className="font-semibold">Ingresos por origen</h2></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{Object.entries({ sale: 0, repair: 0, manual: 0, refund: 0, ...data.summary.bySource }).map(([source, value]) => <div key={source} className="rounded-xl border p-4"><p className="text-sm text-muted-foreground">{sourceLabel[source] || source}</p><p className="mt-1 text-xl font-bold">{money(value)}</p></div>)}</div><p className="mt-3 text-xs text-muted-foreground">Solo ingresos activos del resultado filtrado.</p></section>
    <div className="grid gap-6 lg:grid-cols-[360px_1fr]">
      <section className="rounded-2xl border bg-card/80 p-5 shadow-sm"><h2 className="mb-4 font-semibold">Nuevo movimiento</h2><div className="space-y-3"><select value={type} onChange={e => setType(e.target.value as "income" | "expense")} className="h-10 w-full rounded-lg border bg-background px-3 text-sm"><option value="expense">Egreso</option><option value="income">Ingreso</option></select><Input type="number" min="1" value={amount} onChange={e => setAmount(e.target.value)} placeholder="Valor" /><select value={paymentMethod} onChange={e => setPaymentMethod(e.target.value)} className="h-10 w-full rounded-lg border bg-background px-3 text-sm"><option value="cash">Efectivo</option><option value="card">Tarjeta</option><option value="transfer">Transferencia</option><option value="other">Otro</option></select><Input value={description} onChange={e => setDescription(e.target.value)} placeholder="Descripción" /><Button disabled={saving || !amount} onClick={saveMovement} className="w-full bg-amber-600 hover:bg-amber-700"><Plus className="mr-2 h-4 w-4" />{saving ? "Guardando..." : "Registrar movimiento"}</Button>{message && <p className="text-sm text-muted-foreground">{message}</p>}</div></section>
      <section className="rounded-2xl border bg-card/80 p-5 shadow-sm"><div className="mb-4 flex items-center justify-between gap-3"><div><h2 className="font-semibold">Movimientos</h2><p className="text-xs text-muted-foreground">{active.length} activos · {data.movements.length} encontrados</p></div><Button variant="outline" size="sm" onClick={() => void load()}><RefreshCw className="mr-2 h-4 w-4" />Actualizar</Button></div><div className="space-y-2">{data.movements.length === 0 ? <p className="py-10 text-center text-sm text-muted-foreground">No hay movimientos con estos filtros.</p> : data.movements.map(m => { const voided = m.status === "voided"; return <div key={m._id} className={`flex items-center justify-between gap-3 rounded-xl border p-3 ${voided ? "opacity-60" : ""}`}><div className="flex min-w-0 items-center gap-3"><div className={`rounded-lg p-2 ${voided ? "bg-muted text-muted-foreground" : m.type === "income" ? "bg-emerald-500/10 text-emerald-600" : "bg-red-500/10 text-red-600"}`}>{voided ? <Ban className="h-4 w-4" /> : m.type === "income" ? <ArrowUpCircle className="h-4 w-4" /> : <ArrowDownCircle className="h-4 w-4" />}</div><div className="min-w-0"><p className={`truncate font-medium ${voided ? "line-through" : ""}`}>{m.description || "Movimiento"}</p><p className="text-xs text-muted-foreground">{sourceLabel[m.source] || m.source} · {methodLabel[m.paymentMethod] || m.paymentMethod} · {new Date(m.createdAt).toLocaleString("es-CO")}{voided ? " · ANULADO" : ""}</p>{voided && m.voidReason && <p className="truncate text-xs text-muted-foreground">Motivo: {m.voidReason}</p>}</div></div><div className="flex shrink-0 items-center gap-3"><span className={`font-semibold ${voided ? "text-muted-foreground" : m.type === "income" ? "text-emerald-600" : "text-red-600"}`}>{voided ? "ANULADO" : `${m.type === "income" ? "+" : "-"}${money(Number(m.amount))}`}</span>{!voided && <Button variant="ghost" size="icon" title="Anular movimiento" aria-label="Anular movimiento" disabled={voidingId === m._id} onClick={() => voidMovement(m)}><Ban className="h-4 w-4" /></Button>}</div></div>; })}</div></section>
    </div>
  </main>;
}
